package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

public class PilihGambarCombobox extends javax.swing.JFrame {

    public PilihGambarCombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        lDenji = new javax.swing.JLabel();
        lKageyama = new javax.swing.JLabel();
        lVinlandsaga = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pilihan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel.setLayout(new java.awt.CardLayout());

        lDenji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDenji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/denji.jpg"))); // NOI18N
        imagePanel.add(lDenji, "0");

        lKageyama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKageyama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kageyama.jpg"))); // NOI18N
        lKageyama.setToolTipText("");
        imagePanel.add(lKageyama, "1");

        lVinlandsaga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lVinlandsaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/vinlandsaga.jpg"))); // NOI18N
        imagePanel.add(lVinlandsaga, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Pilih Gambar");
        buttonPanel.add(jLabel1);

        Pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Denji", "Kageyama", "Vinland Saga" }));
        Pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihanActionPerformed(evt);
            }
        });
        buttonPanel.add(Pilihan);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihanActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, String.valueOf(Pilihan.getSelectedIndex()));
    }//GEN-LAST:event_PilihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarCombobox fullFrame = new PilihGambarCombobox();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pilihan;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lDenji;
    private javax.swing.JLabel lKageyama;
    private javax.swing.JLabel lVinlandsaga;
    // End of variables declaration//GEN-END:variables
}
